sonar.projectKey=gadaol-frontend
sonar.sources=src

# 자동생성 파일 제외
sonar.exclusions=src/types/database/database.types.ts

# 무시할 규칙
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S6759
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.tsx
